# Generated by Django 4.2.7 on 2023-12-18 14:20

import car_details.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(upload_to=car_details.models.car_image_upload),
        ),
    ]
