# Generated by Django 4.2.7 on 2023-12-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0003_alter_carmodel_model_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='title',
            field=models.CharField(default='eit', max_length=100),
            preserve_default=False,
        ),
    ]
