# Generated by Django 4.2.7 on 2023-12-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0005_carmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='slug',
        ),
    ]
