# Generated by Django 4.2.7 on 2023-12-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0007_carmodel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
