# Generated by Django 4.2.7 on 2023-12-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0008_remove_carmodel_title_carmodel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
